### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by p2635** [j19sch/fourhourtester#16]
On the homepage: https://www.fourhourtester.net/

- [ ] All the links below 'Blog posts about the four-hour tester' seem to go to a German page not found
- [ ] Test Heuristics cheat sheet links are broken in https://www.fourhourtester.net/exercises/Testdesign.html

**Comment by p2635** [comment]
Test Heuristics links are broken in https://www.fourhourtester.net/exercises/Testdesign.html

**Comment by p2635** [comment]
@j19sch @HelenaJM  are you getting notifications for these? Let me know how I can help, I tried to find the original links but failed to do so

**Comment by j19sch** [comment]
@p2635 I wasn't getting notifications until you tagged me, so thank you for doing so!

The test heuristics cheat sheet can be found here: https://web.archive.org/web/20150217124452/http://testobsessed.com/wp-content/uploads/2011/04/testheuristicscheatsheetv1.pdf And an updated version with a different layout here: https://www.ministryoftesting.com/dojo/lessons/test-heuristics-cheat-sheet

For the blog posts, I don't think the ones from the German site are available anymore. The Internet Archive does have them still, for example the firsts one https://web.archive.org/web/20211028102935/https://www.bredex.de/en/blog/details/the-four-hour-tester-part-i The ones by Ash Winter luckily are still available.

I'll take some time the coming weekend to update the site.

**Comment by p2635** [comment]
Thanks, I didn't get your notification either, weird! @j19sch, let me know if I an contribute. I like the website.

**Comment by p2635** [comment]
Shall we update the article with the MoT version? https://github.com/j19sch/fourhourtester/pull/19

**Comment by j19sch** [comment]
I migrated the repo to https://codeberg.org/joeposaurus/four-hour-tester and the site to https://fourhourtester.smallsheds.garden/index.html. I fixed the broken links as part of that.
