### ISSUE TITLE
Modelling - Evaluation question

### ISSUE THREAD

**Issue by p2635** [j19sch/fourhourtester#17]
URL: https://www.fourhourtester.net/exercises/Modeling.html

In the evaluation section it says:

> For each tour write down 3 things you would want to test.

By the time you get to this part, you would've already toured Google calendar. It's a bit confusing because this task seems to suggest you need to plan it out first. For example, "3 things I want to do a data tour on: Events, tasks and contacts in Google Calendar". But I already tested Google Calendar as a whole?

**Comment by j19sch** [comment]
Good point. That question should be phrased better. The idea is that the tours allow you to learn about the application and that you then in the evaluation come up with test ideas based on what you have learned.
